### PR TITLE
Created template for user.html

### PR DESCRIPTION
**Pull request by BenjaminWalkerBond**
Created input fields for all information outlined in project description. Used regex for input validation.

### CODE REVIEW

**Review by sirisjo — APPROVED** [review]
Looks good to me!

**Review by evanfestrada — APPROVED** [review]
Looks good to me. 

Does the address allow for any special characters? 

Also, we might consider making the states a drop-down selection field like most websites use. This can be something I can look into if you both think that would be a good option.

**Comment by sirisjo** [comment]
that's a good idea, if it's something we can do in html I would be down for incorporating it into this assignment!

**Comment by BenjaminWalkerBond** [comment]
The address doesn’t allow for any special characters. I used regex to validate it. It’s the “pattern=[a-zA-Z0-9-]+” input attribute. 

I agree with the drop down selection menu! Apparently it cannot be done in vanilla HTML5. I’ve looked it up and one of the options is to load an array of all states from a database and display them in a list.

**Pull request merged**
