### PR TITLE
Bens new css

### PR DESCRIPTION
**Pull request by BenjaminWalkerBond**
Replaced Evan's old html with new. Ensured consistent styling across all embedded pages. (Evan, you will still have to tweak some certain things in your html, like your <br> tag areas.

### CODE REVIEW

**Comment by sirisjo** [comment]
Just a suggestion, but it looks like the .css files for all the pages except the main_page are very similar, it might be more clean to have just one .css file that those pages all share, instead of 4 almost duplicate .css files.

**Review by sirisjo — APPROVED** [review]
looks good, but I would recommend sharing 1 .css file for among all pages except main page, for simplicity/consistency

**Comment by BenjaminWalkerBond** [comment]
That’s a good idea! I’ll fix that when I get home tonight.

**Review by evanfestrada — APPROVED** [review]
Thanks, Ben! I'll make some changes to my HTML shortly. The Main Page is looking really good. Well done!

**Pull request merged**
